# Generated by Django 5.1.4 on 2025-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.AddField(
            model_name='forsaleproduct',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='forsaleproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='forsaleproduct',
            name='image',
            field=models.ManyToManyField(blank=True, to='forsale.productimage'),
        ),
    ]
