# Generated by Django 5.1.6 on 2025-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0002_productimage_forsaleproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forsaleproduct',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
