# Generated by Django 5.1.6 on 2025-03-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_realated_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='realated_id',
            new_name='related_id',
        ),
    ]
