# Generated by Django 5.1.4 on 2025-01-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorservice',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
