# Generated by Django 5.1.4 on 2025-01-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productorservice_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productorservice',
            name='image',
        ),
        migrations.AddField(
            model_name='productorservice',
            name='image',
            field=models.ManyToManyField(blank=True, to='shop.productimage'),
        ),
    ]
