# Generated by Django 5.1.6 on 2025-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='contact',
            field=models.CharField(max_length=25),
        ),
    ]
