# Generated by Django 5.1.6 on 2025-03-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorservice',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorservice',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
