# Generated by Django 5.1.4 on 2024-12-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='followed_shops',
            field=models.ManyToManyField(blank=True, related_name='followerwing', to='shop.shop'),
        ),
    ]
