# Generated by Django 5.1.4 on 2025-01-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_followed_shops'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
