# Generated by Django 5.1.6 on 2025-03-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_owner'),
        ('user', '0003_alter_myuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='saved_products_or_services',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='shop.productorservice'),
        ),
    ]
